### ISSUE TITLE
Release on jcenter

### ISSUE THREAD

**Issue by LouisCAD** [feilfeilundfeil/kotlin-native-suspend-function-callback#1]
Hi, did you request jcenter sync for the bintray repository?
Or did you forget to update the README and it's already there?

Having the library on jcenter ensures consumer projects that the artifact can't be removed.

**Comment by jonasbark** [comment]
Hi!

The Annotations part made it to jcenter:
https://jcenter.bintray.com/de/ffuf/kotlin/multiplatform/annotations/

However there was a problem on bintrays part regarding the processor itself: https://jcenter.bintray.com/de/ffuf/kotlin/multiplatform/processor/
They published the wrong package - even though I specifically requested the correct package to be published on jcenter. The correct package (https://bintray.com/beta/#/jonasbark/ffuf/nativesuspendfunction-compiler?tab=overview) is missing the option to publish it on jcenter - but for whatever reasons the wrong package (that apparently is already published) still has the option.

I reported this mistake to bintrays support but I guess due to the fact that I'm not a paying customer I never received an answer unfortunately.

**Comment by jonasbark** [comment]
I now tried to merge the two packages and I'll request to add it to jcenter. Thanks for the reminder!

**Comment by LouisCAD** [comment]
@jonasbark I had an issue with jcenter some time in the past, and despite me not being a paying customer of bintray, they fixed the issue. It took a few days, but they got a solution after clarification.

**Comment by LouisCAD** [comment]
@jonasbark You mean they both have the same group now but are only different artifacts of the same group?

**Comment by jonasbark** [comment]
I contacted them via https://jfrog.com/contact-us/ and all I got was `Can you kindly share which product of JFrog do you use and the level of subscription that you own?` and they never replied again after stating that I'm not a paying customer.

But anyways, the request to add the correct (merged) package was just approved and it's now available on jcenter. I'll adjust the Readme!

**Comment by LouisCAD** [comment]
The maven coordinates didn't change, but all the artifacts are correctly on jcenter?

**Comment by jonasbark** [comment]
Yes
